# Generated by Django 4.1 on 2022-11-05 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='tags',
            field=models.ManyToManyField(to='base.tags'),
        ),
        migrations.CreateModel(
            name='AboutUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_email', models.EmailField(max_length=254, null=True)),
                ('bio', models.TextField(null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=60, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
