# Generated by Django 4.1 on 2022-11-05 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_offer_tags_aboutuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutuser',
            options={'verbose_name': 'AboutUser', 'verbose_name_plural': 'AboutUsers'},
        ),
    ]
