# Generated by Django 4.1 on 2022-11-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_aboutuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuser',
            name='firstname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutuser',
            name='lastname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
