# Generated by Django 4.1 on 2022-10-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_category_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='topic',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
