# Generated by Django 4.1 on 2022-10-28 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_offer_topic_delete_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.RemoveField(
            model_name='location',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='location',
            name='stret',
        ),
    ]
