# Generated by Django 4.1 on 2022-11-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_aboutuser_firstname_aboutuser_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='offer/'),
        ),
    ]
