# Generated by Django 4.1 on 2022-10-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_location_city_remove_location_house_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-updated', '-created'], 'verbose_name': 'offer', 'verbose_name_plural': 'offers'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offer/'),
        ),
    ]
