# Generated by Django 4.1 on 2022-10-31 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_offer_image_alter_offer_price_alter_offer_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
